# Generated by Django 4.2.7 on 2023-12-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='description',
            field=models.CharField(default='No description', max_length=255),
        ),
    ]
